---
- name: download atlassian-crowd tar.gz
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_tmp }}"
    validate_certs: no
    force: no

- name: extract the atlassian-crowd tar.gz
  unarchive:
    copy: no
    creates: "{{ atlassian_crowd_dir }}"
    owner: root
    group: root
    src: "{{ download_tmp }}"
    dest: "{{ atlassian_crowd_basedir }}"

- name: fix directory permissions
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - {path: "{{ atlassian_crowd_dir }}/apache-tomcat/temp",
       owner: "{{ atlassian_crowd_user }}",
       group: "{{ atlassian_crowd_group }}"}
    - {path: "{{ atlassian_crowd_dir }}/apache-tomcat/work",
       owner: "{{ atlassian_crowd_user }}",
       group: "{{ atlassian_crowd_group }}"}
    - {path: "{{ atlassian_crowd_dir }}/apache-tomcat/logs",
       owner: "{{ atlassian_crowd_user }}",
       group: "{{ atlassian_crowd_group }}"}

- name: fix shell script permissions (find)
  find:
    paths: "{{ atlassian_crowd_dir }}"
    file_type: file
    patterns: "*.sh"
    recurse: yes
  register: files_to_change

- name: fix shell script permissions (change)
  file:
    path: "{{ item.path }}"
    state: file
    group: "{{ atlassian_crowd_group }}"
    mode: "g+x"
  with_items: "{{ files_to_change.files }}"
